// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkyKLdouwlfizrCTXzSOrpD8dspdh9Z34',
    appId: '1:518036539574:web:913301d789f07cb2d7be17',
    messagingSenderId: '518036539574',
    projectId: 'rastomozhka',
    authDomain: 'rastomozhka.firebaseapp.com',
    storageBucket: 'rastomozhka.firebasestorage.app',
    measurementId: 'G-MDP4VKSFRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy7bjZSC8zHAmkx3MCs2a-HmLtIj6FjYc',
    appId: '1:518036539574:android:7a6eaa93cb698190d7be17',
    messagingSenderId: '518036539574',
    projectId: 'rastomozhka',
    storageBucket: 'rastomozhka.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpmjug7CP4On1GZpnjSL2sYUAYxYkXksA',
    appId: '1:518036539574:ios:76fd3cef4ab87b0ed7be17',
    messagingSenderId: '518036539574',
    projectId: 'rastomozhka',
    storageBucket: 'rastomozhka.firebasestorage.app',
    iosBundleId: 'com.example.calculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpmjug7CP4On1GZpnjSL2sYUAYxYkXksA',
    appId: '1:518036539574:ios:76fd3cef4ab87b0ed7be17',
    messagingSenderId: '518036539574',
    projectId: 'rastomozhka',
    storageBucket: 'rastomozhka.firebasestorage.app',
    iosBundleId: 'com.example.calculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkyKLdouwlfizrCTXzSOrpD8dspdh9Z34',
    appId: '1:518036539574:web:99fee0ceab9e7bf0d7be17',
    messagingSenderId: '518036539574',
    projectId: 'rastomozhka',
    authDomain: 'rastomozhka.firebaseapp.com',
    storageBucket: 'rastomozhka.firebasestorage.app',
    measurementId: 'G-4P298QDXGX',
  );
}
